---
abstract: 'easy exception catcher with auto rethrow'
author:
  - 'Kazuhiro Osawa E<lt>yappo {@} shibuya {dot} plE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Try-Lite
no_index:
  directory:
    - inc
provides:
  Try::Lite:
    file: lib/Try/Lite.pm
    version: v0.0.2
requires:
  Exporter: 0
  Scalar::Util: 0
  parent: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.2
